### ISSUE TITLE
Lifecycle event history tab is not stable

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#82]
Once you are in NSR->VNFR->"lifecycle event history" (tab), after few seconds the tab looses the focus and move to the default tab. I verified in one machine, please check if you have the same problem.

**Comment by Mr-ZohaibHassan** [comment]
@marcellom 
It's verified it does not stay focused after 10 seconds because, It's keep updating the status of NSR. VNFR is inside NSR. So, If you refresh the parent array, child array also get refreshed. 
It was asked by @lorenzotomasini to refresh it after each 10 seconds.
If you have further questions, please let me know.

**Comment by marcellom** [comment]
It is ok to refresh the NSR as @lorenzotomasini said, but you should keep the basic functionalities working. Try to find a solution about this please.

**Comment by Mr-ZohaibHassan** [comment]
@marcellom This issue was solved, you can double check from your side and can close the issue.
