### ISSUE TITLE
Remove not clickable "Remove Parameter" buttons

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#83]
When a VNF has already configuration parameters, there are many red buttons "Remove Paramenter" which are not clickable. See the screenshot below:
![screen shot 2017-07-03 at 19 35 20](https://user-images.githubusercontent.com/14921749/27803025-a3bd8c2e-6027-11e7-9959-6a71d52076ca.png)
Since they are not clickable, I suggest to don't show them at all. Of course the ones coming from the static VNFD. If the user wants to add a configuration parameter in the GUI, then he can also remove it with the button.

**Comment by Mr-ZohaibHassan** [comment]
@marcellom  I have Fixed the Issue. You can check and Confirm.
@lorenzotomasini  I have fixed the layout as well, because you said that it's taking a lot of space so, I put it in tabular form. Screenshot is below for your reference.
![image](https://user-images.githubusercontent.com/8872102/28027233-b31e2914-6598-11e7-9f5a-8f7e2f6eb58b.png)

**Comment by lorenzotomasini** [comment]
Can you put the configuration key column font to bold ? it is hard to understand for a new user the difference between the columns from my point of view
Cheers
Lorenzo

**Comment by Mr-ZohaibHassan** [comment]
@lorenzotomasini 
Fixed the column
Screenshot is below for further reference.
![image](https://user-images.githubusercontent.com/8872102/28028439-cd7f7692-659c-11e7-9090-ceaf06e46ae6.png)

**Comment by marcellom** [comment]
Tested I can close the issue.
